### ISSUE TITLE
Inactive Instance Shoots Exception

### ISSUE THREAD

**Issue by R00tB33rMan** [MattyHD0/ChatColor#6]
Example Log: https://mclo.gs/UT6tpXJ

**Comment by MattyHD0** [comment]
Fixed in https://github.com/MattyHD0/ChatColor/commit/5f4b3af895eb4fcfb5bc8f52aa2c8065343cc769

**Comment by R00tB33rMan** [comment]
> Fixed in [5f4b3af](https://github.com/MattyHD0/ChatColor/commit/5f4b3af895eb4fcfb5bc8f52aa2c8065343cc769)

Sadly I still receive this warning:
```[07:23:07 WARN]: [me.mattyhd0.chatcolor.lib.hikaricp.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@32718973 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.```
